version: '3.8'
services:
  db:
    image: 'postgres:9.6-alpine'
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: admin
    ports:
      - '15432:5432'
    volumes:
      - 'data:/var/lib/postgresql/data'
    networks:
      - db
  pgadmin:
    image: 'dpage/pgadmin4:4.26'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '16543:80'
    depends_on:
      - db
    networks:
      - db
networks:
  db: null
volumes:
  data: null
